# Generated by Django 5.2.8 on 2025-11-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('season', models.CharField(max_length=100)),
                ('requirements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cause', models.CharField(help_text='e.g., Fungus, Virus, Bacterium', max_length=255)),
                ('symptoms', models.TextField()),
                ('scientific_solution', models.TextField()),
                ('organic_solution', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease_images/')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='farmapp.crop')),
            ],
            options={
                'verbose_name_plural': 'Diseases',
                'unique_together': {('crop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('predicted_disease', models.ForeignKey(blank=True, help_text='The disease predicted by the AI model.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmapp.disease')),
            ],
        ),
    ]
