# Generated by Django 5.2.8 on 2025-11-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={},
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='organic_solution',
            new_name='organic_treatment',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='scientific_solution',
            new_name='scientific_treatment',
        ),
        migrations.AlterUniqueTogether(
            name='disease',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='crop',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='affected_crops', to='farmapp.disease'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='requirements',
            field=models.TextField(help_text='Optimal temperature, soil type, and water requirements.'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='disease',
            name='cause',
            field=models.TextField(help_text='Bacterial, Fungal, Viral, or Deficiency cause.'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='crop_uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='predicted_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='farmapp.disease'),
        ),
        migrations.RemoveField(
            model_name='disease',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='image',
        ),
    ]
