# Generated by Django 5.2.8 on 2025-11-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images/'),
        ),
    ]
