# Generated by Django 5.2.12 on 2026-04-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0005_remove_upload_predicted_disease_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='predicted_disease_name',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.AddField(
            model_name='upload',
            name='predicted_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='farmapp.disease'),
        ),
    ]
