# Generated by Django 5.2.12 on 2026-04-09 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0007_farmerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='crop',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='disease_list', to='farmapp.crop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='cause',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(default=1, upload_to='diseases/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
